name: Commit Log

on:
  push:
    branches:
      - main # or the branch you want to monitor

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # fetch the last 2 commits to get the message from the one before this action runs
      
      - name: Get commit message
        id: commit
        run: echo "::set-output name=message::$(git log --format=%B -n 1 HEAD~1)"

      - name: Create markdown file
        run: |
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          FILENAME="${TIMESTAMP}.md"
          echo "${{ steps.commit.outputs.message }}" > "${FILENAME}"
          
      - name: Commit and push markdown file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add commit message log"
          git push
